### PR TITLE
ba-99 create element for recipe   inventory item ranking

### PR DESCRIPTION
**Pull request by flashback2k14**
@lyio @hetec for review

### CODE REVIEW

**Comment by patrick-hebner** [comment]
Does not work after editing a recipe for me. I entered some ingredients and a recipe with matches for all ingredients - this worked fine. After that I edited the recipe so that amount of ingredients wouldn't be enough anymore. But after reloading the calculation only the new values are shown but test still passes. 

Or is that the right behavior? Shouldn't the calculation recognize that some ingredients aren't sufficiently available?

image

It says everything is good but in real there exist only 500g Nudeln and 4 Tomaten

**Comment by patrick-hebner** [comment]
Why do you only use half of the screen?

**Comment by flashback2k14** [comment]
No automatic reloading at the Moment. The other half is for The planned grocery list reserved. It shows The entered values inside The recipe and not The available inventory items. This needs some work for better matching calculating.

**Comment by patrick-hebner** [comment]
I think we should discuss this next week again. It is not very intuitive for me if it say the recipe and ingredients match if there are not enough ingredients to realize this recipe. What do you think?

**Comment by flashback2k14** [comment]
Yup

**Pull request merged**
