### PR TITLE
ba-116 Wrap add/delete fabs into their own element

### PR DESCRIPTION
**Pull request by lyio**
create new element `socobo-element-buttons`
Move the add/delete-all fabs from socobo-inventory and socobo-recipe-overview to the new element.
Hook up the new element to the existing interfaces
Add new css mixin for the styling of the buttons

### CODE REVIEW

**Comment by lyio** [comment]
@flashback2k14 maybe you can show me why the demo does not work. I'm sure I missed something somewhere.

**Comment by flashback2k14** [comment]
Hmm. Can't See why demo not works. I look into it tomorow.

**Comment by flashback2k14** [comment]
I have found it. You missed The paper-fab import. You only need webcomponents, polymer, fab and your element.

**Comment by flashback2k14** [comment]
LGTM

**Comment by lyio** [comment]
LGTM

**Pull request merged**
