### PR TITLE
ba-105 change font to Roboto Slab,

### PR DESCRIPTION
**Pull request by flashback2k14**
set light accent color to elements add button

https://www.google.com/fonts/specimen/Roboto+Slab#charset

@lyio @hetec for **quick** review

### CODE REVIEW

**Comment by patrick-hebner** [comment]
Is this the recommendation of @cs13dr1?

**Comment by flashback2k14** [comment]
Nope. This is The only recommendation of @cs13dr1 http://www.fontsquirrel.com/fonts/merriweather. This is only a .ttf file.

**Comment by patrick-hebner** [comment]
In my opinion this font doesn't match the purpose of the app since it looks a bit to technical.  But it's a lot more readable so if there are no other suggestions I would agree

**Comment by flashback2k14** [comment]
If you have time to search for a more foody font till 11am today, than happy searching. ;-)

**Comment by lyio** [comment]
I don't really care about fonts. As long as it's readable...so lgtm

**Comment by patrick-hebner** [comment]
lgtm

**Pull request merged**
