### PR TITLE
ba-111 create element for grocery list

### PR DESCRIPTION
**Pull request by flashback2k14**
@lyio @hetec for review

### CODE REVIEW

**Comment by lyio** [comment]
Please do add the jslint config files again and just disable jslint for the dist builds. The dev builds work fine.

One of these days we should look into the lint warnings as well.

**Comment by lyio** [comment]
Two things I noticed:
1. Seems odd that you have to check an item when you click the delete button directly
2. It is kind of unexpected that the list item disappears when you click edit.

**Comment by flashback2k14** [comment]
Tomorow or you add it back.

**Comment by lyio** [comment]
https://ba-pm-presentation.myjetbrains.com/youtrack/issue/ba-122, there, happy? :p

**Comment by flashback2k14** [comment]
1. I know  i look into it tomorow.
2. i only handle add and remove. I remove it if you edit it and save the old not changed or The New changed.

**Comment by flashback2k14** [comment]
@lyio to your Points:
1. fixed - no checkbox needed to single delete / move an item
2. i don't change The behaviour at this time. It needs a lot of rewrite and rethink and i like it. :-)

**Comment by lyio** [comment]
LGTM

**Comment by flashback2k14** [comment]
LGTM

**Pull request merged**
