### PR TITLE
ba-151 send grocery list to user as email

### PR DESCRIPTION
**Pull request by flashback2k14**
- Add an option to send the actual grocery list to the registered user email address
  - Note: for testing you need a real email address
- other changes:
  - remove media queries from socobo auth, because it cause layout issues on smaller notebook ans mobile optimization to not planned at the moment
  - Bugfix routing: now the address bar shows always the right route
  - Add an option to "GoToHome" if you click the application name

@lyio @hetec for review

### CODE REVIEW

**Comment by flashback2k14** [comment]
The backend is now more stable after todays rewrite. It doesn't crash anymore with a failed mail send. :-)

**Comment by flashback2k14** [comment]
can we merge this!? @lyio @hetec

**Comment by lyio** [comment]
lgtm

**Comment by flashback2k14** [comment]
lgtm

**Pull request merged**
