### PR TITLE
Ba 53 pass user info to sub elements

### PR DESCRIPTION
**Pull request by flashback2k14**

### CODE REVIEW

**Comment by lyio** [comment]
I actually agree with @hetec that instead of passing in three separate properties we could use a UserInfo or UserLogin object:

``` javascript
{
  'expires': '1234567',
  'userId': 'fooBar',
  'firebaseUrl': 'https://foo.bar.firebase.io'
}
```

Since the `userId` is our top level entry point into the database we could append it to the url for passing around.

**Comment by flashback2k14** [comment]
What is the benefit for using an object instead the properties? I can't see.

**Comment by lyio** [comment]
There are in fact several benefits:
- less clutter/better organization as we can group the properties that logically belong together
- better extesibility: if we find out that we need additional properties later on, we can add them to the object instead of having to go around patching up all the elements.

**Comment by flashback2k14** [comment]
if you want an object, you get an object!

**Comment by flashback2k14** [comment]
please update issue ba-53 and I implement the changes!

**Comment by flashback2k14** [comment]
@lyio

**Pull request merged**
