### PR TITLE
ba-123 add information and disclaimer, point

### PR DESCRIPTION
**Pull request by flashback2k14**
on register to our own disclaimer

**Note:** strange behavior with the disclamer pdf on dist folder. if i
copy the pdf to elements/disclamer the anchor tag looks at
elements/socobo-auth/disclamer and if i copy the pdf to
elements/socobo-auth/disclamer the anchor tag looks to
elements/disclamer

@lyio @hetec for **quick** review

### CODE REVIEW

**Comment by patrick-hebner** [comment]
Whats the goal of the disclaimer? Haven't we learned that we don't have to provide these information because all these things are fixed in the articles you are referencing to?
Another point is that the german text looks quite strange in the context of a english application. IMO

**Comment by flashback2k14** [comment]
I don't know, but i think it's better to have one.

**Comment by lyio** [comment]
I'm with @hetec here. But this way, the page isn't empty. So, whatever

lgtm

**Comment by patrick-hebner** [comment]
To get finished

lgtm

**Comment by flashback2k14** [comment]
lgtm

**Pull request merged**
